[[bookmarks]]
i = 0
j = 0
url = "http://m.176xsw.com/7/111/read/99575.html"
title = "放开那个女巫- 第一章 从今天开始做王子"
type = "ebook"

[[bookmarks]]
i = 12
j = 0
url = "http://m.176xsw.com/7/111/read/99575.html"
title = "放开那个女巫- 第一章 从今天开始做王子"
type = "ebook"

[[bookmarks]]
i = 15
j = 0
url = "https://www.xbookcn.com/book/chest/14.htm"
title = "第十三章 色魔正面挑战"
type = "ebook"

[[bookmarks]]
i = 5
j = 0
url = "https://m.banzhuer.com/1_1251/352271_8.html"
title = "大学刑法课（七）_大学刑法课_rescueme_第二版主网"
type = "ebook"

[[bookmarks]]
i = 13
j = 19
url = "https://m.banzhuer.com/1_1251/352289_3.html"
title = "大学刑法课（十九）_大学刑法课_rescueme_第二版主网"
type = "ebook"

[[bookmarks]]
i = 2
j = 0
url = "https://m.banzhuer.com/1_1251/352320_3.html"
title = "大学刑法课46_大学刑法课_rescueme_第二版主网"
type = "ebook"

[[bookmarks]]
i = 0
j = 127
url = "https://exhentai.org/s/8154e762d7/1366417-13"
title = "(C93) [Hitori de dekirumon. (Kain)] chou kyokudai kain mura"
type = "eimg"

[[bookmarks]]
i = 1
j = 290
url = "https://manhwahentai.com/manhwa/the-sharehouse/chapter-36"
title = "The Sharehouse - Chapter 36 - Manhwa Hentai"
type = "eimg"

[[bookmarks]]
i = 1
j = 1084
url = "https://manhwahentai.com/manhwa/the-sharehouse/chapter-36"
title = "The Sharehouse - Chapter 36 - Manhwa Hentai"
type = "eimg"

[[bookmarks]]
i = 5
j = 1434
url = "https://manhwahentai.com/manhwa/the-sharehouse/chapter-37"
title = "The Sharehouse - Chapter 37 - Manhwa Hentai"
type = "eimg"

[[bookmarks]]
i = 0
j = 0
url = "58a75d70b610c9fc54fe5f4c#0"
title = "第一章 陨落的天才"
type = "zsbook"

[[bookmarks]]
i = 3
j = 19
url = "579b93ae561763dd2d2382e6#98"
title = "第一百零章 威胁"
type = "zsbook"

[[bookmarks]]
i = 0
j = 19
url = "https://m.banzhuer.com/1_1251/352282_3.html"
title = "大学刑法课（十四）_大学刑法课_rescueme_第二版主网"
type = "ebook"

[[bookmarks]]
i = 2
j = 0
url = "https://m.banzhuer.com/1_1251/352282_3.html"
title = "大学刑法课（十四）_大学刑法课_rescueme_第二版主网"
type = "ebook"

[[bookmarks]]
i = 6
j = 0
url = "5b2a2ac9c4d0bb0100a067b2#2"
title = "正文卷 第3章  噩梦级任务"
type = "zsbook"

